### PR TITLE
add google analytics and scarf tracking

### PR DESCRIPTION
**Pull request by Roshanjossey**

### CODE REVIEW

**Review by makram93 — APPROVED** [review]
LGTM! Could you also please help setup the Netlify secrets for this repo? It needs [`AUTH_TOKEN1` and `SITE_ID`](https://github.com/jina-ai/now/blob/main/.github/workflows/label-pr.yml#L55) but I could not get it from other repo and I am not sure if I should use my personal login for this.

**Comment by Roshanjossey** [comment]
@makram93 I don't have access to jina dev bot's netlify secrets either. However, anybody who can access secrets of core repo can copy it here (or make it organisation secrets so all repos in the org can access it)

I'd rather you go with jina dev bot's secrets than your own.

**Comment by florian-hoenicke** [comment]
@Roshanjossey @makram93 How do we proceed?

**Comment by Roshanjossey** [comment]
@florian-hoenicke, this PR can be merged. Netlify secrets are for getting previews working correctly. I suggest someone taking that up.

**Comment by makram93** [comment]
> @florian-hoenicke, this PR can be merged. Netlify secrets are for getting previews working correctly. I suggest someone taking that up.

I agree - I will try setting it up with Deepankar. This PR can be merged!

**Comment by florian-hoenicke** [comment]
alright - thanks

**Pull request merged**
