### PR TITLE
fix: remove search field in playground

### PR DESCRIPTION
**Pull request by IyadhKhalfallah**
---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

### CODE REVIEW

**Review by violenil — APPROVED** [review]
LGTM!

**Review by jupyterjazz — COMMENTED** [review]
do you know why CI is failing?

**Comment by IyadhKhalfallah** [comment]
> do you know why CI is failing?

@jupyterjazz Actually, these are not related to this PR. I think it's a common problem happening to everyone!

**Review by jupyterjazz — APPROVED** [review]
LGTM!

**Comment by IyadhKhalfallah** [comment]
Closed because @florian-hoenicke addressed it in another PR.

**Pull request closed without merging**
