### PR TITLE
docs(tracking): update external links' source

### PR DESCRIPTION
**Pull request by Roshanjossey**

### CODE REVIEW

**Review by alexcg1 — APPROVED** [review]
LGTM :+1:

**Review by florian-hoenicke — APPROVED** [review]
LGTM

**Comment by florian-hoenicke** [comment]
@Roshanjossey Thanks for the pr.
Is the cd triggered now automatically, or do you have to deploy it?

**Comment by Roshanjossey** [comment]
I think docs deployment is still manual. I'll trigger it

**Pull request merged**
