### PR TITLE
fix: import executors to make visible for yaml construct

### PR DESCRIPTION
**Pull request by violenil**
---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

### CODE REVIEW

**Review by jupyterjazz — APPROVED** [review]
:rocket:

**Review by jupyterjazz — COMMENTED** [review]
we should move this to `conftest` because `test_custom_da_with_tags.py` and `test_api_key.py` need this too

**Comment by jupyterjazz** [comment]
I just tried locally and didn't fix the issue :(

**Review by joschkabraun — APPROVED** [review]

**Comment by violenil** [comment]
> I just tried locally and didn't fix the issue :(

@jupyterjazz can you try again?

**Pull request merged**
