### PR TITLE
feat: no head deployments

### PR DESCRIPTION
**Pull request by florian-hoenicke**

### CODE REVIEW

**Review by makram93 — APPROVED** [review]
LGTM

**Comment by florian-hoenicke** [comment]
@joschkabraun thanks for the feedback. I added the requested test which also considers the fine-tuning case and therefore tests different number of pods

**Review by joschkabraun — APPROVED** [review]

**Comment by joschkabraun** [comment]
The currently thrown error can be resolved by `moving kwargs.pop('dataset', None)`  from after `run_backend.run(...)` to above it in `run_all_k8s.py`

**Comment by florian-hoenicke** [comment]
thanks for the feedback - fixed

**Pull request merged**
