### PR TITLE
Feat add nest modalities

### PR DESCRIPTION
**Pull request by violenil**
This PR adds a new hybrid modality to the supported modalities (text+image) and updates the modalities of the `text_to_text_and_image` app.

### CODE REVIEW

**Review by makram93 — COMMENTED** [review]
There are other functions as well to be overridden. Will that be tackled in another PR?

**Review by azayz — COMMENTED** [review]
What about the vector modality ?

**Review by makram93 — APPROVED** [review]
LGTM!

**Review by jupyterjazz — APPROVED** [review]
LGTM!

**Review by joschkabraun — APPROVED** [review]
LGTM!

**Pull request merged**
