### PR TITLE
feat: expose scores in playground results

### PR DESCRIPTION
**Pull request by violenil**
In this PR, the score breakdown can be retrieved and presented in the playground.

---

- [x] This PR references an open issue
- [ ] Added a test (NA: playground has no tests)
- [x] Updated the documentation
- [x] Added a screenshot of a successful customer deployment

### CODE REVIEW

**Comment by violenil** [comment]
Working customer deployment screenshot:
Screenshot 2023-02-08 at 12 31 27

**Review by makram93 — APPROVED** [review]
LGTM!
Just a small query: If the state of the toggle button for the breakdown score is changed does the result section gets cleared?

**Comment by violenil** [comment]
> Just a small query: If the state of the toggle button for the breakdown score is changed does the result section gets cleared?

Try it out 😉 No, the results don't get cleared, it just hides the scores again (incase you have deactivated it) or shows the overall score (if you have done a search request with it previously un-toggled).

**Review by florian-hoenicke — APPROVED** [review]
Great work!

**Pull request merged**
