### PR TITLE
test: add local folder e2e tests

### PR DESCRIPTION
**Pull request by jupyterjazz**
Closes https://github.com/jina-ai/now/issues/985

Adding local and remote e2e tests for local folder

---

- [x] This PR references an open issue
- [x] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

### CODE REVIEW

**Review by azayz — APPROVED** [review]
LGTM

**Review by florian-hoenicke — APPROVED** [review]
Nice to increase the test coverage

**Comment by florian-hoenicke** [comment]
Followup ticket needed

**Comment by jupyterjazz** [comment]
https://github.com/jina-ai/now/issues/1003

**Pull request merged**
