### PR TITLE
fix: add logo

### PR DESCRIPTION
**Pull request by slettner**

### CODE REVIEW

**Comment by slettner** [comment]
@makram93 is this the right folder for the logo?

**Comment by slettner** [comment]
Also, is there a way to increment the docker tag manually? The CI seems to fail because of that

**Comment by joschkabraun** [comment]
> Also, is there a way to increment the docker tag manually? The CI seems to fail because of that

You are right. You need to manually increment the `docker_bff_playground_tag` here: https://github.com/jina-ai/now/blob/main/now/run_all_k8s.py#L17

**Comment by makram93** [comment]
Thanks for the PR but as Florian has already pushed the logo in this commit: [`bed631a`](https://github.com/jina-ai/now/commit/bed631a9f191c0c4d43feaee2e19e2452e2af8d3) I am closing this PR.

**Pull request closed without merging**
